# Generated by Django 4.1.3 on 2022-12-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(default='sin@email.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='phone',
            field=models.CharField(default='0', max_length=80),
            preserve_default=False,
        ),
    ]
