# Generated by Django 4.1.3 on 2023-01-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persona_email_persona_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='email',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='phone',
            new_name='sintoma',
        ),
    ]
